---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: hub-ca-trust-placementbinding
  namespace: default
placementRef:
  name: hub-ca-trust-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: hub-ca-trust-distribution
    apiGroup: policy.open-cluster-management.io
    kind: Policy
