apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-audit-kernel-modules
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/audit/rules.d/75-kernel-modules.rules
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain,%23%20M5%3A%20Audit%20Kernel%20Module%20Loading%20%28E8%20Compliance%29%0A%23%20Documentation%3A%20https%3A%2F%2Fsebrandon1.github.io%2Fcompliance-scripts%2Fversions%2F4.21%2Fgroups%2FM5.html%0A%0A%23%20Module%20loading%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20init_module%20-S%20finit_module%20-k%20module_load%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20init_module%20-S%20finit_module%20-k%20module_load%0A%0A%23%20Module%20unloading%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20delete_module%20-k%20module_unload%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20delete_module%20-k%20module_unload%0A
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-audit-kernel-modules
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/audit/rules.d/75-kernel-modules.rules
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain,%23%20M5%3A%20Audit%20Kernel%20Module%20Loading%20%28E8%20Compliance%29%0A%23%20Documentation%3A%20https%3A%2F%2Fsebrandon1.github.io%2Fcompliance-scripts%2Fversions%2F4.21%2Fgroups%2FM5.html%0A%0A%23%20Module%20loading%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20init_module%20-S%20finit_module%20-k%20module_load%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20init_module%20-S%20finit_module%20-k%20module_load%0A%0A%23%20Module%20unloading%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20delete_module%20-k%20module_unload%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20delete_module%20-k%20module_unload%0A
