apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-audit-dac-modification
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/audit/rules.d/75-dac-modification.rules
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain,%23%20M3%3A%20Audit%20DAC%20Modifications%20%28E8%20Compliance%29%0A%23%20Documentation%3A%20https%3A%2F%2Fsebrandon1.github.io%2Fcompliance-scripts%2Fversions%2F4.21%2Fgroups%2FM3.html%0A%0A%23%20chmod%20syscalls%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20chmod%20-S%20fchmod%20-S%20fchmodat%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-k%20perm_mod%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20chmod%20-S%20fchmod%20-S%20fchmodat%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-k%20perm_mod%0A%0A%23%20chown%20syscalls%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20chown%20-S%20fchown%20-S%20fchownat%20-S%20lchown%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-k%20perm_mod%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20chown%20-S%20fchown%20-S%20fchownat%20-S%20lchown%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-k%20perm_mod%0A
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-audit-dac-modification
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/audit/rules.d/75-dac-modification.rules
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain,%23%20M3%3A%20Audit%20DAC%20Modifications%20%28E8%20Compliance%29%0A%23%20Documentation%3A%20https%3A%2F%2Fsebrandon1.github.io%2Fcompliance-scripts%2Fversions%2F4.21%2Fgroups%2FM3.html%0A%0A%23%20chmod%20syscalls%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20chmod%20-S%20fchmod%20-S%20fchmodat%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-k%20perm_mod%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20chmod%20-S%20fchmod%20-S%20fchmodat%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-k%20perm_mod%0A%0A%23%20chown%20syscalls%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20chown%20-S%20fchown%20-S%20fchownat%20-S%20lchown%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-k%20perm_mod%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20chown%20-S%20fchown%20-S%20fchownat%20-S%20lchown%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-k%20perm_mod%0A
