apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-audit-network
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/audit/rules.d/75-network-config.rules
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain,%23%20M8%3A%20Audit%20Network%20Config%20%28E8%20Compliance%29%0A%23%20Documentation%3A%20https%3A%2F%2Fsebrandon1.github.io%2Fcompliance-scripts%2Fversions%2F4.21%2Fgroups%2FM8.html%0A%0A%23%20Network%20syscalls%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20sethostname%20-S%20setdomainname%20-k%20system-locale%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20sethostname%20-S%20setdomainname%20-k%20system-locale%0A%0A%23%20Network%20config%20files%0A-w%20%2Fetc%2Fissue%20-p%20wa%20-k%20system-locale%0A-w%20%2Fetc%2Fissue.net%20-p%20wa%20-k%20system-locale%0A-w%20%2Fetc%2Fhosts%20-p%20wa%20-k%20system-locale%0A-w%20%2Fetc%2Fhostname%20-p%20wa%20-k%20system-locale%0A-w%20%2Fetc%2Fsysconfig%2Fnetwork%20-p%20wa%20-k%20system-locale%0A
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-audit-network
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/audit/rules.d/75-network-config.rules
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain,%23%20M8%3A%20Audit%20Network%20Config%20%28E8%20Compliance%29%0A%23%20Documentation%3A%20https%3A%2F%2Fsebrandon1.github.io%2Fcompliance-scripts%2Fversions%2F4.21%2Fgroups%2FM8.html%0A%0A%23%20Network%20syscalls%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20sethostname%20-S%20setdomainname%20-k%20system-locale%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20sethostname%20-S%20setdomainname%20-k%20system-locale%0A%0A%23%20Network%20config%20files%0A-w%20%2Fetc%2Fissue%20-p%20wa%20-k%20system-locale%0A-w%20%2Fetc%2Fissue.net%20-p%20wa%20-k%20system-locale%0A-w%20%2Fetc%2Fhosts%20-p%20wa%20-k%20system-locale%0A-w%20%2Fetc%2Fhostname%20-p%20wa%20-k%20system-locale%0A-w%20%2Fetc%2Fsysconfig%2Fnetwork%20-p%20wa%20-k%20system-locale%0A
