apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-audit-time
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/audit/rules.d/75-time-change.rules
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain,%23%20M6%3A%20Audit%20Time%20Modifications%20%28E8%20Compliance%29%0A%23%20Documentation%3A%20https%3A%2F%2Fsebrandon1.github.io%2Fcompliance-scripts%2Fversions%2F4.21%2Fgroups%2FM6.html%0A%0A%23%20Time%20syscalls%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20adjtimex%20-S%20settimeofday%20-k%20time-change%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20adjtimex%20-S%20settimeofday%20-S%20stime%20-k%20time-change%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20clock_settime%20-k%20time-change%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20clock_settime%20-k%20time-change%0A%0A%23%20Localtime%20file%20watch%0A-w%20%2Fetc%2Flocaltime%20-p%20wa%20-k%20time-change%0A
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-audit-time
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/audit/rules.d/75-time-change.rules
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain,%23%20M6%3A%20Audit%20Time%20Modifications%20%28E8%20Compliance%29%0A%23%20Documentation%3A%20https%3A%2F%2Fsebrandon1.github.io%2Fcompliance-scripts%2Fversions%2F4.21%2Fgroups%2FM6.html%0A%0A%23%20Time%20syscalls%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20adjtimex%20-S%20settimeofday%20-k%20time-change%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20adjtimex%20-S%20settimeofday%20-S%20stime%20-k%20time-change%0A-a%20always%2Cexit%20-F%20arch%3Db64%20-S%20clock_settime%20-k%20time-change%0A-a%20always%2Cexit%20-F%20arch%3Db32%20-S%20clock_settime%20-k%20time-change%0A%0A%23%20Localtime%20file%20watch%0A-w%20%2Fetc%2Flocaltime%20-p%20wa%20-k%20time-change%0A
