---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .metadata.name | default "ca-issuer" }}
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ca:
    secretName: {{ .spec.ca.secretName | default "root-ca-secret" }}
